name: player_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.36
  audio_session: ^0.1.16
  just_audio_background: ^0.0.1-beta.11
  flutter_native_splash: ^2.4.5
  cached_network_image: ^3.2.1
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.2
  path_provider: ^2.0.14
  audio_service: ^0.18.15
  flutter_cache_manager: ^3.3.0
  rxdart: ^0.27.7
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.3.2
  provider: ^6.1.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/